### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by funkyzooink** [funkyzooink/little-ninja#4]
There is a Json file with about 30 lines.
`https://github.com/funkyzooink/little-ninja/blob/master/Resources/json/localization/en.json`

Translate to any language and add it to the localization folder as `countrycode.json`

**Comment by pecikoza** [comment]
Hey, I could do it in french if you want :)

**Comment by vherasme** [comment]
Hello. I could do the translation to Spanish

**Comment by ArturBa** [comment]
Assign me for polish
