### ISSUE TITLE
Translate play store description

### ISSUE THREAD

**Issue by funkyzooink** [funkyzooink/little-ninja#42]
In the folder `store` is the English play store description `en.txt`

Currently little ninja has German, Spanish, French, Norwegian, polish, Portuguese, Turkish  translations.

We would need the store descriptions in these languages to add them in a future update. Translations should be saved in the same location as `country code.txt`

**Comment by ArturBa** [comment]
Assign me to polish ;)

**Comment by guipleite** [comment]
I can work in the portuguese translation, if that's ok

**Comment by daviddetorres** [comment]
I can work in the Spanish translation.

**Comment by daviddetorres** [comment]
Pulled:  #45

**Comment by alicankustemur** [comment]
I'm working on Turkish.

**Comment by alaguillog** [comment]
I'm working on French

**Comment by josteinl** [comment]
I'll do Norwegian. Added a PR #55.

Could you please add "hacktoberfest" topic to their repository: 

```
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.
```
